#!/usr/bin/env python3
"""Regenerate training+finetune YAML configs against the unified bundle layout.

The configs in `configs/` are generated by the GS40+GS55+GS33 training notebook
on a Windows machine with UNC paths baked in. After moving the bundle to a
new machine (laptop SSD, Rockfish scratch, etc.), run this script to rewrite
the YAMLs against the local paths.

Reads the bundle root from $STARDIST_DATASETS_ROOT (or --root). Reads the
splits CSVs from each cohort to enumerate train/val stems. Writes two YAMLs
to `configs/`: one for the main 35-epoch run, one for the finetune.

Usage on Rockfish:
    export STARDIST_DATASETS_ROOT=/scratch4/dwirtz1/$USER/stardist_datasets
    python shared_convnext_stardist_decoder/regenerate_configs.py \\
        --tag gs40_gs55_gs33_v4_base \\
        --backbone facebook/convnextv2-base-22k-224
"""
from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

import yaml

# Make the package importable when running this file directly from the repo root.
_HERE = Path(__file__).resolve()
sys.path.insert(0, str(_HERE.parents[1]))

from shared_convnext_stardist_decoder.aux_codes.cohorts import (
    cohort_paths, resolve_datasets_root,
)
from shared_convnext_stardist_decoder.aux_codes.train_utils import (
    build_training_config,
)


COHORT_NAMES = ["GS40", "GS55", "GS33"]

CLASS_NAMES = [
    "bone", "brain", "eye", "heart", "lungs", "gi", "liver", "spleen",
    "pancreas", "kidney", "mesokidney", "collagen", "ear", "nontissue",
    "thymus", "thyroid", "bladder", "skull", "spleen2",
]

HPARAMS: dict[str, dict] = {
    "main": dict(
        epochs=35, batch_size=8, lr=5e-5, lr_min=1e-6, weight_decay=0.03,
        freeze_backbone_epochs=10,
        loss_w_prob=2.0, loss_w_dist=0.15, loss_w_cls=1.0, loss_w_inst=0.25,
        cls_semantic_dim=128, num_workers=8,
    ),
    "finetune": dict(
        epochs=15, batch_size=8, lr=1e-5, lr_min=1e-7, weight_decay=0.03,
        freeze_backbone_epochs=5,
        loss_w_prob=2.0, loss_w_dist=0.15, loss_w_cls=1.0, loss_w_inst=0.25,
        cls_semantic_dim=128, num_workers=8,
    ),
}


def _read_stems(p: Path) -> list[str]:
    with p.open(encoding="utf-8", newline="") as f:
        rows = list(csv.reader(f))
    if rows and rows[0][0].strip().lower() in {"stem", "name", "id", "tile", "filename"}:
        rows = rows[1:]
    return list(dict.fromkeys(
        r[0].strip() for r in rows if r and r[0].strip()
    ))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=None,
                    help="Bundle root. Defaults to $STARDIST_DATASETS_ROOT.")
    ap.add_argument("--tag", default="gs40_gs55_gs33_v4_base",
                    help="Experiment tag; appears in the YAML filename and experiment_name.")
    ap.add_argument("--backbone", default="facebook/convnextv2-base-22k-224",
                    help="HF backbone id.")
    ap.add_argument("--ckpt-parent", default=None,
                    help="Where training will write checkpoints. "
                         "Defaults to <bundle_root>/_runs.")
    ap.add_argument("--out-dir", default=None,
                    help="Where to write the YAMLs. Defaults to <repo>/shared_convnext_stardist_decoder/configs.")
    args = ap.parse_args()

    root = resolve_datasets_root(
        explicit=args.root,
        candidates=(),  # env var fallback handled inside resolve
    )
    cohorts = {n: cohort_paths(n, root) for n in COHORT_NAMES}

    # Combine + dedupe stems across cohorts.
    train_stems: list[str] = []
    val_stems: list[str] = []
    for name, c in cohorts.items():
        t = _read_stems(c["train_split"])
        v = _read_stems(c["val_split"])
        print(f"  {name}: {len(t):,} train, {len(v):,} val")
        train_stems += t
        val_stems += v
    train_stems = list(dict.fromkeys(train_stems))
    val_stems = list(dict.fromkeys(val_stems))
    print(f"Combined: {len(train_stems):,} train, {len(val_stems):,} val")

    ckpt_parent = Path(args.ckpt_parent or (root / "_runs"))
    out_dir = Path(args.out_dir or (_HERE.parent / "configs"))
    out_dir.mkdir(parents=True, exist_ok=True)

    for stage in ("main", "finetune"):
        hp = HPARAMS[stage]
        suffix = "" if stage == "main" else "_finetune"
        experiment = f"convnext_stardist_mt_{args.tag}{suffix}"
        fname = (f"config_{args.tag}_multitask.yaml" if stage == "main"
                 else f"config_finetune_{args.tag}.yaml")
        ckpt_out = ckpt_parent / f"run_{args.tag}{suffix}"
        ckpt_out.mkdir(parents=True, exist_ok=True)

        primary = next(iter(cohorts.values()))
        cfg = build_training_config(
            experiment_name=experiment,
            train_images_dir=primary["train_images"],
            inst_labels_dir=primary["train_labels"],
            ckpt_out=ckpt_out,
            train_stems=train_stems, val_stems=val_stems,
            class_names=CLASS_NAMES,
            epochs=hp["epochs"], batch_size=hp["batch_size"],
            lr=hp["lr"], lr_min=hp["lr_min"], weight_decay=hp["weight_decay"],
            freeze_backbone_epochs=hp["freeze_backbone_epochs"],
            loss_w_cls=hp["loss_w_cls"], loss_w_inst=hp["loss_w_inst"],
            loss_w_dist=hp["loss_w_dist"], cls_semantic_dim=hp["cls_semantic_dim"],
        )
        cfg["model"]["backbone"]      = args.backbone
        cfg["train"]["loss_w_prob"]   = hp["loss_w_prob"]
        cfg["train"]["num_workers"]   = hp["num_workers"]
        # Always write paths in POSIX form so the YAML is portable.
        cfg["data"]["train_sources"] = [
            {"images_dir": Path(c["train_images"]).as_posix(),
             "labels_dir": Path(c["train_labels"]).as_posix()}
            for c in cohorts.values()
        ]
        cfg["data"]["val_sources"] = [
            {"images_dir": Path(c["val_images"]).as_posix(),
             "labels_dir": Path(c["val_labels"]).as_posix()}
            for c in cohorts.values()
        ]
        # Also normalize the top-level paths build_training_config wrote.
        cfg["data"]["train_images_dir"] = Path(cfg["data"]["train_images_dir"]).as_posix()
        cfg["data"]["train_labels_dir"] = Path(cfg["data"]["train_labels_dir"]).as_posix()
        cfg["data"]["val_images_dir"]   = Path(cfg["data"]["val_images_dir"]).as_posix()
        cfg["data"]["val_labels_dir"]   = Path(cfg["data"]["val_labels_dir"]).as_posix()
        cfg["checkpoint"]["out_dir"]    = Path(cfg["checkpoint"]["out_dir"]).as_posix()

        out_path = out_dir / fname
        out_path.write_text(
            yaml.dump(cfg, default_flow_style=False, sort_keys=False),
            encoding="utf-8",
        )
        print(f"  wrote {out_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
